### ISSUE TITLE
adapter for JDBC.jl

### ISSUE THREAD

**Issue by ExpandingMan** [wookay/Octo.jl#1]
If you want an easy but inefficient way of supporting just about any imaginable database, you might consider writing an adapter for [JDBC.jl](https://github.com/JuliaDatabases/JDBC.jl).  It might complicate things lightly because the JVM has to be started and later shut down, but otherwise I think it would be straightforward.

I might be able to offer some help if I have time.

**Comment by wookay** [comment]
I just made an interface for the JDBC adapter.
https://github.com/wookay/Octo.jl/blob/master/src/backends/JDBC.jl
https://github.com/wookay/Octo.jl/tree/master/test/adapters/jdbc/

Thanks for your interests!

**Comment by ExpandingMan** [comment]
Nice!

I've only recently overhauled JDBC.jl after a period of semi-abandonment, so let me know if you come across any kinks to be worked out.

I forgot to mention: JDBC.jl itself should be all ready for Julia 0.7, but JavaCall.jl still needs to be updated.  It should be relatively straightforward, so it'll definitely be done by the full 1.0 release, but I don't know when I'll get to it.

**Comment by wookay** [comment]
merged the JDBC backend.
https://github.com/wookay/Octo.jl/commit/dd7ac4d678b6f34d9ae85c4cb88d17b5498f0e97

**Comment by wookay** [comment]
closing the issue, finally supported in Octo v0.2.1
