### ISSUE TITLE
SQL insert statement generation problem

### ISSUE THREAD

**Issue by huaxk** [wookay/Octo.jl#10]
`to_sql([INSERT INTO heres VALUES ("test1", "SR")])`
generate sql: 
`INSERT INTO heres VALUES 'test1', 'SR'`
but current insert sql is:
`INSERT INTO heres VALUES ('test1', 'SR')`
the problem should be to insert less parentheses in the part of VALUES.

**Comment by wookay** [comment]
Fixed at master. thanks.
