### ISSUE TITLE
The generated insert statement is missing parentheses

### ISSUE THREAD

**Issue by huaxk** [wookay/Octo.jl#13]
`[INSERT INTO users (users.name, users.email) VALUES ("Jick", "Jick@dd.com")]`
generated sql:
`INSERT INTO users users.name, users.email VALUES ('Jick', 'Jick@dd.com')`
perhaps missing parentheses and remove "users." before column's name.

**Comment by wookay** [comment]
thanks. made a PR
https://github.com/wookay/Octo.jl/pull/14/files#diff-55f514bda671b216f88c9df6c89cb06eR62

**Comment by wookay** [comment]
the PR #14 merged at the master. thanks.

**Comment by huaxk** [comment]
Thanks for your quick feeback!
