### ISSUE TITLE
Support for composite keys

### ISSUE THREAD

**Issue by onsails** [wookay/Octo.jl#18]
Let's say I have a PostgreSQL table `create table foos (id bigint, ts bigint, name text, primary key (id, ts))`. Is there an ability to query items from this table by pk using `Repo`?

**Comment by wookay** [comment]
try something like
https://github.com/wookay/Octo.jl/blob/master/test/octo/schema.jl#L21
```
Schema.model(User, table_name="users", primary_keys=("pk1", "pk2"))
Repo.get(User, (pk1=1, pk2=2))
```

**Comment by onsails** [comment]
thanks!

**Comment by wookay** [comment]
@prettynatty  this will change to `primary_key`
```
Schema.model(User, table_name="users", primary_key=("pk1", "pk2"))
Repo.get(User, (pk1=1, pk2=2))
```
