### ISSUE TITLE
Getting the primary key of an inserted item?

### ISSUE THREAD

**Issue by Wieke** [wookay/Octo.jl#19]
Hi

I was wondering if there is a neat way of getting the primary key of an inserted item. I can't seem to find any hint of it in the documentation, tests or source. The only way I've found so far requires me to resort to raw sql, which I'd rather avoid. (I need the key to use as a foreign key.)

This one works for sqlite:

```julia
Repo.query(Raw("SELECT last_insert_rowid()"))
```

Thanks

**Comment by wookay** [comment]
Hello. thanks for the issue.
I've imitated [Ecto's one](https://hexdocs.pm/ecto/Ecto.Adapter.Schema.html#c:insert/6).
here are tests and routines for each adapters.

for example,
```julia
inserted = Repo.insert!(Post, (title="hello", body="world"))
inserted.id
```

* postgresql
  - test https://github.com/wookay/Octo.jl/blob/master/test/adapters/postgresql/execute_result_test.jl#L27
  - internal code https://github.com/wookay/Octo.jl/blob/master/src/Repo.jl#L345
```
INSERT ... RETURNING pk
```

* mysql
  - test https://github.com/wookay/Octo.jl/blob/master/test/adapters/mysql/execute_result_test.jl#L34
  - internal code https://github.com/wookay/Octo.jl/blob/master/src/Backends/MySQL.jl#L66
```
last_insert_id = MySQL.insertid(conn)
```

* sqlite
  - test https://github.com/wookay/Octo.jl/blob/master/test/adapters/sqlite/execute_result_test.jl#L34
  - internal code https://github.com/wookay/Octo.jl/blob/master/src/Backends/SQLite.jl#L63
```
last_insert_id = SQLite.last_insert_rowid(db)
```

any suggestion would be great.

**Comment by Wieke** [comment]
Nice. The `insert!` function returning the inserted object with id or just the id is the kind of behaviour I was expecting, so this looks fine to me.
