### ISSUE TITLE
Ram Usage

### ISSUE THREAD

**Issue by furkankaradas** [wookay/Octo.jl#42]
Hi,

Thank you for this repo. But I have a problem. I am inserting data using "Repo.query" in PostgreSql database. The data is big (14 Million rows). When inserting the data, ram usage very increasing, finally system give error(Server closed). I am reading one by one and, inserting 20 rows inserting in db. Julia is using low ram but postgres always increasing (I'm looking at the task manager). 

Thank you for helping.

**Comment by wookay** [comment]
see `LibPQ.CopyIn`
https://invenia.github.io/LibPQ.jl/dev/#COPY
