### ISSUE TITLE
function request: hope support DuckDB.jl

### ISSUE THREAD

**Issue by zsz00** [wookay/Octo.jl#45]
hope support  [DuckDB.jl](https://github.com/kimmolinna/DuckDB.jl) in Octo.jl. 

DuckDB is an in-process SQL OLAP database such as sqlite3.

**Comment by wookay** [comment]
hi. 
because of DuckDB.jl doesn't support the prepared statements,
https://github.com/kimmolinna/DuckDB.jl/blob/main/src/DuckDB.jl#L176

I couldn't support things like `Repo.insert!`.
https://github.com/wookay/Octo.jl/blob/master/src/Backends/DuckDB.jl#L37

here's a test.
https://github.com/wookay/Octo.jl/blob/master/test/adapters/duckdb/repo_test.jl

**Comment by zsz00** [comment]
Thank you very much for your quick follow-up. 

How can we push duckdb.jl to support this?

**Comment by wookay** [comment]
it's already opened that issue on the DuckDB.jl issues. that is

Implement  DBInterface.jl
https://github.com/kimmolinna/DuckDB.jl/issues/2

**Comment by kimmolinna** [comment]
@zsz00, I will look at this.

**Comment by zsz00** [comment]
@wookay   Julia Client & C API Extensions   https://github.com/duckdb/duckdb/pull/3253#issue-1172873353

- DBInterface.jl is now fully supported 
- Support for [prepared statements](https://github.com/Mytherin/duckdb/blob/julia/tools/juliapkg/test/test_prepare.jl)
- [All data types](https://github.com/Mytherin/duckdb/blob/julia/tools/juliapkg/test/test_all_types.jl) are supported in the result fetch, including composite and complex data types (lists, structs, etc)
- [Scanning data frames](https://github.com/Mytherin/duckdb/blob/julia/tools/juliapkg/test/test_df_scan.jl) is supported
- Support for creating [table functions](https://github.com/Mytherin/duckdb/blob/julia/tools/juliapkg/test/test_table_function.jl) and [replacement scans](https://github.com/Mytherin/duckdb/blob/julia/tools/juliapkg/test/test_replacement_scan.jl) in pure Julia
- Support for [configuration parameters](https://github.com/Mytherin/duckdb/blob/julia/tools/juliapkg/test/test_config.jl)

**Comment by kimmolinna** [comment]
This means that @mytherin will update DuckDB_jll soon and they will take over also DuckDB.jl.

**Comment by zsz00** [comment]
Now DuckDB.jl is taked over by DuckDB. And registed new release. 
Can you continue this request ??  @wookay

**Comment by wookay** [comment]
yeah. that's cool.
but it still needs the updating DuckDB_jll.jl
 https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl
```
ERROR: LoadError: Unrecognized configuration option "external_threads"
Stacktrace:
  [1] set_config(config::DuckDB.Config, name::String, option::String)
    @ DuckDB ~/.julia/dev/duckdb/tools/juliapkg/src/config.jl:27
```

I got the working local tests by building the duckdb (don't use the DuckDB_jll).
```shell
~/.julia/dev/duckdb $  make
```

checkout the `JULIA_DUCKDB_LIBRARY` for ENV.
```julia
         ENV["JULIA_DUCKDB_LIBRARY"] = dylib
```
https://github.com/wookay/Octo.jl/blob/master/test/adapters/duckdb/repo_test.jl#L6


```shell
~/.julia/dev/Octo/test $  julia runtests.jl  adapters/duckdb
1/1 adapters/duckdb/repo_test.jl
[ Info: DROP TABLE IF EXISTS items
┌ Info: CREATE TABLE items(item VARCHAR, value DECIMAL(10,2), count INTEGER)
└
[ Info: INSERT INTO items (item, value, count) VALUES ($1, $2, $3)    (item = "Jeans", value = 20.0, count = 1), (item = "hammer", value = 42.2, count = 2)
[ Info: SELECT * FROM items
[ Info: SELECT * FROM items WHERE item = 'Jeans'
[ Info: DELETE FROM items WHERE item = 'Jeans'
[ Info: DELETE FROM items WHERE item = 'Jeans'
[ Info: SELECT * FROM items
    Pass: 7  (compile: 18.63, elapsed: 22.18 seconds)
✅  All 7 tests have been completed.  (compile: 18.63, elapsed: 22.18 seconds)
```

**Comment by zsz00** [comment]
@Mytherin, Can you make a new release and new [DuckDB_jll.jl](https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl)

**Comment by wookay** [comment]
#47 Octo v0.2.10 supports DuckDB now.

**Comment by zsz00** [comment]
cool
