### ISSUE TITLE
Repo.insert! one field error

### ISSUE THREAD

**Issue by huaxk** [wookay/Octo.jl#7]
When i use Repo insert one field into postgresql database:
`Repo.insert!(Role, (name="tom",))`
`INFO: INSERT INTO roles (name) VALUES $1   (name = "gdfdf",)`
`ERROR: ERROR:  syntax error at or near "$1"`
`LINE 1: INSERT INTO roles (name) VALUES $1`
I got error?it not generator correct sql.

**Comment by wookay** [comment]
can you provide more things like
```
Repo.execute(Raw("""CREATE TABLE IF NOT EXISTS roles (
                     name VARCHAR(255)
                )"""))
blah blah..
```

you can get more examples for this from
https://github.com/wookay/Octo.jl/tree/master/test/adapters/postgresql

**Comment by huaxk** [comment]
Table DDL：
```
CREATE TABLE roles(
  id integer PRIMARY KEY,
  name VARCHAR(255)
);
```
If you insert data with two columns, not problem. 
`Repo.insert!(Role, (id=3, name="tom",))`
The generated SQL is as follows:
`INSERT INTO roles(id, name) VALUES ($1, $2)   (id = 3, name= "tom")`

but if you insert data with one column:
`Repo.insert!(Role, (name="tom",))`
 the generated SQL is as follows:
`INSERT INTO roles (name) VALUES $1 (name = "tom",)`
The error message is：
```
ERROR: ERROR: syntax error at or near "$1"
LINE 1: INSERT INTO roles (name) VALUES $1
                                        ^
```
There seems to be a problem with the generated SQL?

**Comment by wookay** [comment]
thanks for the issue.
it's fixed into the master branch.
https://github.com/wookay/Octo.jl/blob/master/test/adapters/postgresql/repo_test.jl#L99

**Comment by huaxk** [comment]
Thanks for your quick response!
